version: '2.0'
services:
  apache:
    restart: always  
    build: ./apache
    ports:
    - "80"
    volumes:
    - /var/www/html:/usr/local/apache2/htdocs
    stdin_open: true # -i
    tty: true # -t
  sublime:
    image: jess/sublime-text-3
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /var/www/html:/home/code
    environment:
    - DISPLAY=$DISPLAY
  browser: 
    build: ./browser
    volumes: 
    - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
    - DISPLAY=$DISPLAY
    stdin_open: true # -i
    tty: true # -t 
